[package]
name = "pyaccelsx"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyaccelsx"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
rust_xlsxwriter = "0.75.0"
